"""
Dispatch Module for Project Sentinel.
Handles the delivery of security reports via SMTP email and Webhooks.
"""
import smtplib
import json
import requests
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from typing import List, Optional, Dict, Any
from config import (
    SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, SMTP_FROM, SMTP_TO,
    WEBHOOK_URL, logger
)

class Dispatcher:
    def __init__(self):
        self.smtp_host = SMTP_HOST
        self.smtp_port = SMTP_PORT
        self.smtp_user = SMTP_USER
        self.smtp_pass = SMTP_PASS
        self.smtp_from = SMTP_FROM
        self.smtp_to = SMTP_TO
        self.webhook_url = WEBHOOK_URL

    def send_email(self, subject: str, markdown_body: str, attachments: List[Dict[str, Any]] = None):
        """Sends an HTML email with a professional SOC dashboard wrapper."""
        if not all([self.smtp_host, self.smtp_user, self.smtp_pass, self.smtp_to]):
            logger.warning("SMTP configuration incomplete. Skipping email dispatch.")
            return

        import markdown
        html_content = markdown.markdown(markdown_body)
        
        # Professional HTML Wrapper
        styled_html = f"""
        <html>
        <head>
            <style>
                body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }}
                .container {{ width: 90%; margin: auto; padding: 20px; border: 1px solid #ddd; border-top: 5px solid #004a99; }}
                .header {{ background-color: #f4f4f4; padding: 10px; text-align: center; border-bottom: 1px solid #ddd; }}
                .footer {{ font-size: 0.8em; color: #777; margin-top: 20px; text-align: center; border-top: 1px solid #eee; padding-top: 10px; }}
                h1 {{ color: #004a99; }}
                blockquote {{ border-left: 5px solid #eee; padding-left: 15px; font-style: italic; color: #555; }}
                pre {{ background: #f9f9f9; padding: 10px; border: 1px solid #ccc; overflow-x: auto; }}
                code {{ font-family: 'Courier New', Courier, monospace; background: #f4f4f4; padding: 2px 4px; }}
                .briefing {{ background-color: #e7f3ff; padding: 15px; border-radius: 5px; margin-bottom: 20px; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>🛡️ Project Sentinel Security Report</h1>
                    <p>Wazuh AI Intelligence Pipeline</p>
                </div>
                <div class="content">
                    {html_content}
                </div>
                <div class="footer">
                    <p>Automated Report generated by Project Sentinel. Please do not reply to this email.</p>
                </div>
            </div>
        </body>
        </html>
        """

        msg = MIMEMultipart()
        msg['Subject'] = subject
        msg['From'] = self.smtp_from or self.smtp_user
        msg['To'] = self.smtp_to

        msg.attach(MIMEText(styled_html, 'html'))

        if attachments:
            for att in attachments:
                try:
                    part = MIMEApplication(att['content'], Name=att['filename'])
                    part['Content-Disposition'] = f'attachment; filename="{att["filename"]}"'
                    msg.attach(part)
                except Exception as e:
                    logger.error(f"Failed to attach file {att.get('filename')}: {e}")

        try:
            logger.info(f"Sending email to {self.smtp_to}: {subject}")
            with smtplib.SMTP(self.smtp_host, self.smtp_port) as server:
                server.starttls()
                server.login(self.smtp_user, self.smtp_pass)
                server.send_message(msg)
            logger.info("Email sent successfully.")
        except Exception as e:
            logger.error(f"Error sending email: {e}")

    def send_webhook(self, briefing: str):
        """Sends a briefing to a webhook via POST."""
        if not self.webhook_url:
            logger.warning("Webhook URL not set. Skipping webhook dispatch.")
            return

        payload = {
            "text": briefing,
            "source": "Project Sentinel",
            "type": "executive_briefing"
        }

        try:
            logger.info(f"Sending briefing to webhook: {self.webhook_url}")
            response = requests.post(self.webhook_url, json=payload, timeout=10)
            response.raise_for_status()
            logger.info("Webhook sent successfully.")
        except Exception as e:
            logger.error(f"Error sending webhook: {e}")

if __name__ == "__main__":
    # Test
    logging.basicConfig(level=logging.INFO)
    dispatcher = Dispatcher()
    # dispatcher.send_webhook("Test briefing")
