"""
Dispatch Module for Project Sentinel.
Handles the delivery of security reports via SMTP email and Webhooks.
"""
import smtplib
import json
import requests
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
from typing import List, Optional, Dict, Any
from config import (
    SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, SMTP_FROM, SMTP_TO,
    WEBHOOK_URL, logger
)

class Dispatcher:
    def __init__(self):
        self.smtp_host = SMTP_HOST
        self.smtp_port = SMTP_PORT
        self.smtp_user = SMTP_USER
        self.smtp_pass = SMTP_PASS
        self.smtp_from = SMTP_FROM
        self.smtp_to = SMTP_TO
        self.webhook_url = WEBHOOK_URL

    def send_email(self, subject: str, markdown_body: str, attachments: List[Dict[str, Any]] = None):
        """Sends a professional email with dashboard styling and attachments."""
        if not all([self.smtp_host, self.smtp_user, self.smtp_pass, self.smtp_to]):
            logger.warning("SMTP configuration incomplete. Skipping email dispatch.")
            return

        import markdown
        # Convert Markdown to HTML with advanced extensions for better data structuring
        html_content = markdown.markdown(markdown_body, extensions=['tables', 'fenced_code', 'toc'])

        # Professional HTML Wrapper with improved data structure styling
        styled_html = f"""
        <html>
        <head>
            <style>
                body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #2c3e50; margin: 0; padding: 0; background-color: #f4f7f6; }}
                .container {{ width: 95%; max-width: 1000px; margin: 30px auto; padding: 0; background: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 15px rgba(0,0,0,0.1); border: 1px solid #e1e4e8; }}
                .header {{ background: linear-gradient(135deg, #004a99 0%, #0066cc 100%); color: #ffffff; padding: 30px 20px; text-align: center; }}
                .header h1 {{ margin: 0; font-size: 24px; letter-spacing: 1px; }}
                .header p {{ margin: 10px 0 0; opacity: 0.9; font-size: 14px; }}
                .content {{ padding: 30px; }}
                .footer {{ background-color: #f8f9fa; font-size: 12px; color: #7f8c8d; padding: 20px; text-align: center; border-top: 1px solid #eee; }}
                h2, h3 {{ color: #2980b9; border-bottom: 2px solid #ecf0f1; padding-bottom: 8px; margin-top: 30px; }}

                /* Data Table Styling */
                table {{ width: 100%; border-collapse: collapse; margin: 20px 0; font-size: 13px; background: white; }}
                th {{ background-color: #f2f4f7; color: #34495e; font-weight: 600; padding: 12px 10px; border: 1px solid #dee2e6; text-align: left; }}
                td {{ padding: 10px; border: 1px solid #dee2e6; vertical-align: top; }}
                tr:nth-child(even) {{ background-color: #f9f9f9; }}
                tr:hover {{ background-color: #f1f4f6; }}

                /* Tactical Highlights */
                blockquote {{ border-left: 5px solid #3498db; padding: 15px 20px; margin: 20px 0; background: #eef7fb; border-radius: 0 4px 4px 0; }}
                pre {{ background: #2c3e50; color: #ecf0f1; padding: 15px; border-radius: 6px; overflow-x: auto; font-family: 'Consolas', 'Courier New', monospace; line-height: 1.4; }}
                code {{ font-family: 'Consolas', monospace; background: #f0f2f5; padding: 2px 6px; border-radius: 4px; color: #e74c3c; font-weight: bold; }}

                /* Briefing Box */
                .briefing {{ background-color: #fff3cd; padding: 20px; border-radius: 6px; border-left: 5px solid #ffc107; margin: 20px 0; color: #856404; }}
                .briefing ul {{ margin: 0; padding-left: 20px; }}

                /* Tag Styling */
                .tag {{ display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: bold; text-transform: uppercase; margin-right: 5px; }}
                .tag-high {{ background-color: #e74c3c; color: white; }}
                .tag-med {{ background-color: #f39c12; color: white; }}
            </style>
        </head>
        <body>
            <div class="container">
                <div class="header">
                    <h1>Project Sentinel Forensic Report</h1>
                    <p>Wazuh AI Intelligence Pipeline · Automated Daily Security Audit</p>
                </div>
                <div class="content">
                    {html_content}
                </div>
                <div class="footer">
                    <p><b>Confidential SOC Telemetry</b><br>Generated by Project Sentinel. Access restricted to authorized personnel.<br>© 2026 Project Sentinel Engine</p>
                </div>
            </div>
        </body>
        </html>
        """

        # Create a container for the email
        msg = MIMEMultipart('mixed')
        msg['Subject'] = subject
        msg['From'] = self.smtp_from or self.smtp_user
        msg['To'] = self.smtp_to

        # Create alternative container (HTML + Text fallback)
        msg_alternative = MIMEMultipart('alternative')
        msg.attach(msg_alternative)

        # Attach text and html versions
        msg_alternative.attach(MIMEText(markdown_body, 'plain'))
        msg_alternative.attach(MIMEText(styled_html, 'html'))

        if attachments:
            for att in attachments:
                try:
                    part = MIMEApplication(att['content'], Name=att['filename'])
                    part['Content-Disposition'] = f'attachment; filename="{att["filename"]}"'
                    msg.attach(part)
                except Exception as e:
                    logger.error(f"Failed to attach file {att.get('filename')}: {e}")

        try:
            logger.info(f"Sending styled email to {self.smtp_to}: {subject}")
            with smtplib.SMTP(self.smtp_host, self.smtp_port, timeout=30) as server:
                server.starttls()
                server.login(self.smtp_user, self.smtp_pass)
                server.send_message(msg)
            logger.info("Email sent successfully.")
        except Exception as e:
            logger.error(f"Error sending email: {e}")


    def send_webhook(self, briefing: str):
        """Sends a briefing to a webhook via POST."""
        if not self.webhook_url:
            logger.warning("Webhook URL not set. Skipping webhook dispatch.")
            return

        payload = {
            "text": briefing,
            "source": "Project Sentinel",
            "type": "executive_briefing"
        }

        try:
            logger.info(f"Sending briefing to webhook: {self.webhook_url}")
            response = requests.post(self.webhook_url, json=payload, timeout=10)
            response.raise_for_status()
            logger.info("Webhook sent successfully.")
        except Exception as e:
            logger.error(f"Error sending webhook: {e}")

if __name__ == "__main__":
    # Test
    logging.basicConfig(level=logging.INFO)
    dispatcher = Dispatcher()
    # dispatcher.send_webhook("Test briefing")
